---
name: Rclone Snapshot Sync
version: '1.6.0'
slug: rclone
description: Sync snapshots to another devices
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: application
init: false
boot: auto
ingress: true
ingress_port: 5572
ports:
  5572/tcp: null
ports_description:
  5572/tcp: Web configuration GUI (not required for ingress)
map:
  - backup:rw
  - ssl:ro
options:
  cron: "0 * * * *"
  destination: "<drive>:<path>"
  sync_command: sync
  prune:
    rules: ""
    cron: ""
    delete: false
  credentials:
    username: homeassistant
    password: homeassistant
  tls:
    ssl: false
    certfile: fullchain.pem
    keyfile: privkey.pem
  protected_only: false
schema:
  cron: str
  destination: str
  sync_command: list(sync|copy|move)
  prune:
    rules: str
    cron: str
    delete: bool
  credentials:
    username: str
    password: str
  tls:
    ssl: bool
    certfile: str
    keyfile: str
  protected_only: bool
